models/Createactivity.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "createactivity".
 *
 * @property int $activityId
 * @property int $ticketId
 * @property string $activityBy
 * @property string $customer
 * @property string $activity
 * @property string $comments
 * @property string $mopName
 * @property string $activityLevel
 * @property string $product
 * @property string $patch
 * @property string $description
 * @property string $outcome
 * @property string $output
 * @property string $activityStatus
 * @property int $id_mop
 * @property string $managerApproval
 * @property string $approvalComment
 *
 * @property Mop $mop
 * @property Scheduleactivity $scheduleactivity
 */
class Createactivity extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    const SCENARIO_SRH_ACT = 'srh_act';

    const SCENARIO_DIST_ACT = 'dist_act';

    public $start;
    public $end;
    public $id;
    public $customerName;
    public $resourceName;
    public $approval;
    public $status;

    public $startDate;
    public $endDate;
    public $filter;

    public $date;

    public static function tableName()
    {
        return 'createactivity';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [

	    [['startDate','endDate','filter','date'], 'required', 'on' => [self::SCENARIO_DIST_ACT]],

            [['start','end','id','customerName','resourceName','approval','status'], 'required', 'on' => [self::SCENARIO_SRH_ACT]],

            [['ticketId', 'activityBy', 'customer', 'activity', 'activityLevel', 'product', 'description'], 'required'],

            [['ticketId', 'id_mop'], 'integer'],

            [['activityBy', 'customer', 'mopName', 'product', 'activityStatus','managerApproval'], 'string', 'max' => 200],

            [['activity', 'comments', 'description', 'outcome', 'output'], 'string', 'max' => 1000],

            [['activityLevel', 'patch'], 'string', 'max' => 100],

            [['ticketId', 'mopName'], 'unique', 'targetAttribute' => ['ticketId', 'mopName']],

            [['id_mop'], 'unique'],

	    [['approvalComment'], 'string', 'max' => 500],

	    ['ticketId','match','pattern'=>'/^((?!(0))[0-9]{4,5}$)/'],

	    ['activity','match','pattern'=>'/^[A-Z a-z 0-9.]{1,100}$/'],

            ['mopName', 'required', 'when' => function ($model) {
                return $model->activityBy == '1';
            }, 'whenClient' => "function (attribute, value) {
                    //alert($('#createactivity-activityby').val());
                    return $('#createactivity-activityby').val() == '1';
            }"],

            [['id_mop'], 'exist', 'skipOnError' => true, 'targetClass' => Mop::className(), 'targetAttribute' => ['id_mop' => 'mopId']],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'activityId' => 'Activity ID',
            'ticketId' => 'Ticket ID',
            'activityBy' => 'Activity By',
            'customer' => 'Customer',
            'activity' => 'Activity',
            'comments' => 'Comments',
            'mopName' => 'Mop Name',
            'activityLevel' => 'Activity Level',
            'product' => 'Product',
            'patch' => 'Patch',
            'description' => 'Description',
            'outcome' => 'Outcome',
            'output' => 'Output',
            'activityStatus' => 'Activity Status',
            'id_mop' => 'Id Mop',
	    'managerApproval' => 'Manager Approval',
            'approvalComment' => 'Approval Comment',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
	public function getMop(){

        return $this->hasOne(Mop::className(), ['mopId' => 'id_mop']);
    }
	
    public function getScheduleactivity(){
        
        return $this->hasOne(Scheduleactivity::className(), ['id' => 'activityId']);

    }

    public function getOperatorsName(){

        return $this->hasOne(Operator::className(),['operatorId'=>'customer']);

    }
	
	public function getMopsName(){

        return $this->hasOne(Mop::className(),['mopId'=>'mopName']);

    }

    public function getActivitybyNames(){

        return $this->hasOne(Activityby::className(),['activityById'=>'activityBy']);

    }

    public function sendStatusUpdateAlert() {


        $sql = "SELECT ticketId,scheduleId AS scheduleId ,scheduleTimeSL AS scheduleTimeSL,scheduleTimeOther AS scheduleTimeOther,L1Resource,L2Resource,L3Resource,activity.activity as activity,statusAlert,l1.username AS L1Mail,l2.username AS L2Mail,l3.username AS L3Mail,l1.firstname AS L1Name,l2.firstname AS L2Name,l3.firstname AS L3Name,activity.activityStatus as activityStatus FROM scheduleactivity left Join user l1 on l1.id=scheduleactivity.L1Resource left Join user l2 on l2.id=scheduleactivity.L2Resource left Join user l3 on l3.id=scheduleactivity.L3Resource left Join createactivity activity on activity.activityId=scheduleactivity.id WHERE statusAlert=0";
        //$sql = "SELECT ticketId,scheduleId AS scheduleId ,scheduleTimeSL AS scheduleTimeSL,scheduleTimeOther AS scheduleTimeOther,L1Resource,L2Resource,L3Resource,activity.activity as activity,statusAlert,l1.levelMail AS L1Mail,l2.levelMail AS L2Mail,l3.levelMail AS L3Mail,l1.levelName AS L1Name,l2.levelName AS L2Name,l3.levelName AS L3Name,activity.activityStatus as activityStatus FROM scheduleactivity left Join level l1 on l1.levelId=scheduleactivity.L1Resource left Join level l2 on l2.levelId=scheduleactivity.L2Resource left Join level l3 on l3.levelId=scheduleactivity.L3Resource left Join createactivity activity on activity.activityId=scheduleactivity.id WHERE statusAlert=0";

        $connection = Yii::$app->getDb();

        $results = $connection->createCommand($sql)->queryAll();

        if ($results) {

            foreach ($results as $result) {

            $status = $result['activityStatus'];

            if ($status=="Successfully Completed" or $status=="Partially Successful" or $status=="Failed") {

                if($result['L1Resource'] && $result['L1Mail']){
                            
                    $sql1 = "SELECT o.operatorName AS Customer,o.region AS Region,o.manager AS Manager,u.username AS ManagerMail FROM createactivity left Join operator o on o.operatorId=createactivity.customer left Join manager m on m.region=o.region left join user u on m.user_id=u.id WHERE ticketId=$result[ticketId]";

                    $connection = Yii::$app->getDb();

                    $results1 = $connection->createCommand($sql1)->queryAll();

                    if($results1){

                        foreach ($results1 as $result1) {

                            if($result1['Manager'] && $result1['Region']){

                                if($result['L2Mail'] && $result['L3Mail']){

                                    $send = Yii::$app->mailer->compose()
                                                ->setFrom('support@globalwavenet.com')
                                                ->setTo($result['L1Mail'])
                                                ->setCc(array($result['L2Mail'],$result['L3Mail'],$result1['ManagerMail']))
                                                ->setSubject('Activity Completion Alert')
                                                ->setHtmlBody("Hi $result[L1Name],<br><br>The activity:$result[activity], scheduled at $result[scheduleTimeSL] was completed with the status of $result[activityStatus].<br><br>L1 Resource:$result[L1Name]<br>L2 Resource:$result[L2Name]<br>L3 Resource:$result[L3Name]<br>Manager:$result1[Manager]<br><br>Regards,<br>Operation Assistance<br>Wavenet Support")
                                                ->send();
                                }
                                else{

                                    if($result['L2Mail']){
                                        $send = Yii::$app->mailer->compose()
                                            ->setFrom('support@globalwavenet.com')
                                            ->setTo($result['L1Mail'])
                                            ->setCc(array($result['L2Mail'],$result1['ManagerMail']))
                                            ->setSubject('Activity Completion Alert')
                                            ->setHtmlBody("Hi $result[L1Name],<br><br>The activity:$result[activity], scheduled at $result[scheduleTimeSL] was completed with the status of $result[activityStatus].<br><br>L1 Resource:$result[L1Name]<br>L2 Resource:$result[L2Name]<br>L3 Resource:$result[L3Name]<br>Manager:$result1[Manager]<br><br>Regards,<br>Operation Assistance<br>Wavenet Support")
                                            ->send();
                                    }
                                    else if($result['L3Mail']){
                                        $send = Yii::$app->mailer->compose()
                                            ->setFrom('support@globalwavenet.com')
                                            ->setTo($result['L1Mail'])
                                            ->setCc(array($result['L3Mail'],$result1['ManagerMail']))
                                            ->setSubject('Activity Completion Alert')
                                            ->setHtmlBody("Hi $result[L1Name],<br><br>The activity:$result[activity], scheduled at $result[scheduleTimeSL] was completed with the status of $result[activityStatus].<br><br>L1 Resource:$result[L1Name]<br>L2 Resource:$result[L2Name]<br>L3 Resource:$result[L3Name]<br>Manager:$result1[Manager]<br><br>Regards,<br>Operation Assistance<br>Wavenet Support")
                                            ->send();
                                }
                                    else{
                                        $send = Yii::$app->mailer->compose()
                                            ->setFrom('support@globalwavenet.com')

models/Rca.php
<?php

namespace app\models;

use Yii;
use app\models\Ticketinfo;
use app\models\RcaSearch;

/**
 * This is the model class for table "rca".
 *
 * @property int $rcaId
 * @property int $ticketId
 * @property string $openDate
 * @property string $sharedDate
 * @property string $RCAName
 * @property string $operator
 * @property string $issueDescription
 * @property string $RCACreator
 * @property string $linkToRCA
 */
class Rca extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */

    const SCENARIO_SRH_STR = 'srh_str';
    const SCENARIO_SRH_EN = 'srh_en';
    const SCENARIO_SRH_ID = 'srh_id';
    const SCENARIO_SRH_OPR = 'srh_opr';
    const SCENARIO_SRH_CTR = 'srh_ctr';

    const SCENARIO_DIST_RCA = 'dist_rca';

    public $start;
    public $end;
    public $id;
    public $operatorName;
    public $creator;
    public $startDate;
    public $endDate;
    public $filter;

    public static function tableName()
    {
        return 'rca';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [

            [['start'], 'required', 'on' => [self::SCENARIO_SRH_STR]],

            [['end'], 'required', 'on' => [self::SCENARIO_SRH_EN]],

            [['id'], 'required', 'on' => [self::SCENARIO_SRH_ID]],

            [['operatorName'], 'required', 'on' => [self::SCENARIO_SRH_OPR]],

           // [['creator'], 'required', 'on' => [self::SCENARIO_SRH_CTR]],

	    [['startDate','endDate','filter'], 'required', 'on' => [self::SCENARIO_DIST_RCA]],

            [['ticketId', 'openDate', 'RCAName', 'operator', 'issueDescription', /*'RCACreator',*/ 'linkToRCA'], 'required'],

            [['ticketId'], 'integer'],

            //[['ticketId'], 'validateticketId'],

            [['openDate', 'sharedDate'], 'safe'],

            [['RCAName', 'issueDescription', 'linkToRCA'], 'string', 'max' => 500],

            [['operator'], 'string', 'max' => 200],

            [['RCACreator'], 'string', 'max' => 100],

	    [['ticketId', 'RCAName'], 'unique', 'targetAttribute' => ['ticketId', 'RCAName']],

	    ['ticketId','match','pattern'=>'/^((?!(0))[0-9]{4,5}$)/'],

	    ['RCAName','match','pattern'=>'/^(RCA)(\_)([A-Z][(A-Z)(a-z)\-]+)(\_)((?!(0))[0-9]{4,5})(\_)([A-Z][a-z\-]+)(\_)(([0-2][0-9]|(3)[0-1])(((0)[0-9])|((1)[0-2]))\d{4})(\_)([v][1-9]$)/'],

	    /*['RCAName','match','pattern'=>'/^(RCA)(\_)(Tigo-Bolivia|Millicom-Tanzania|Hutch-SriLanka|Etisalat-SriLanka|Telecom-SriLanka|Airtel-SriLanka|Ooredoo-Maldives|IAF:ALU-India|TATA-India|DTAC-Thailand|TrueMove-Thailand|Millicom-Ghana|Vini-Tahiti|Millicom-Chad|Millicom-Senagal|Safaricom-Kenya|Vodafone-New Zealand|Tigo-Honduras|Intelli-Australia|Tigo-Colombia|Cellcard-Cambodia|Tigo-ElSalvador|Tigo-Paraguay|Smart-Cambodia|Laogw-Laos)(\_)((?!(0))[0-9]{4,5})(\_)([A-Z][a-z\-]+)(\_)(([0-2][0-9]|(3)[0-1])(((0)[0-9])|((1)[0-2]))\d{4})(\_)([v][1-9]$)/'],*/

        ];
    }

    

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'rcaId' => 'Rca ID',
            'ticketId' => 'Ticket ID',
            'openDate' => 'Open Date',
            'sharedDate' => 'Shared Date',
            'RCAName' => 'Rcaname',
            'operator' => 'Operator',
            'issueDescription' => 'Issue Description',
            'RCACreator' => 'Rcacreator',
            'linkToRCA' => 'Link To Rca',
        ];
    }

    public function getOperatorsName(){
        
        return $this->hasOne(Operator::className(),['operatorId'=>'operator']);

    }

    public function getCreatorsName(){
         return $this->hasOne(User::className(),['id'=>'RCACreator']);
       //Pxx return $this->hasOne(Creator::className(),['createrId'=>'RCACreator']);

    }

    
}

views/createactivity/approveform.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use kartik\date\DatePicker;
use kartik\datetime\DateTimePicker;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Rca */
/* @var $form yii\widgets\ActiveForm */
?>                    
                    <div class="modal-body">
                            <!-- <form class="form-horizontal"> -->
                            <?php $form = ActiveForm::begin(['options' => ['id' => 'Update-form','class'=>'form-horizontal']]) ?>
                                <div class="row">
                                    <div class="box-body boxpad">

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Ticket ID</label>
                                                <div class="col-sm-8" >
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->ticketId;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Activity</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->activity;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Schedule Time SL</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo @$model->scheduleactivity->scheduleTimeSL;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Schedule Time Other</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo @$model->scheduleactivity->scheduleTimeOther;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">L1 Resource</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo @$model->scheduleactivity->level1ResourceName->firstname;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">L2 Resource</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo @$model->scheduleactivity->level2ResourceName->firstname;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">L3 Resource</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo @$model->scheduleactivity->level3ResourceName->firstname;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Customer</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo @$model->operatorsName->operatorName;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Manager Approval</label>
                                                <!-- <div class="col-sm-10"> -->
                                                    <?= $form->field($model, 'managerApproval',['options' => ['class' => 'col-sm-8']])->radioList(array('1'=>'Approve',2=>'Reject'))->label(false);?>
                                                <!-- </div> -->
                                            </div>
                                        </div>
                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label class="col-sm-4 control-label">Comments </label>
                                                    <?= $form->field($model, 'approvalComment',['options' => ['class' => 'col-sm-8']])->textarea(['rows' => '3','maxlength' => true,'placeholder' => 'Comments'])->label(false);?>
                                                </div>
                                        </div>

                                    </div>
                                </div> 
                            <!-- </form> -->                                                       
                        </div>

                        <div class="modal-footer">
                            <!-- ?= Html::button('Close', ['class' => 'btn btn-default','name' => 'closeUpdate', 'id' => 'closeUpdate']) ?-->
                            <?= Html::submitButton('Save', ['class' => 'btn btn-primary','name' => 'update', 'id' => 'update']) ?>
                        </div>
                        <?php ActiveForm::end() ?>
<?php
$script = <<< JS
$( document ).ready(function() {
       
        $('#closeApprove').click(function() {
             window.parent.closeApproveModal();
         });  
    });
JS;

$this->registerJs($script);
?>

views/createactivity/mopviewform.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Rca */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="modal-body">
                            <!-- <form class="form-horizontal"> -->
                            <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data', 'id' => 'View-form', 'class' => 'form-horizontal']]) ?>
                                <div class="row">
                                    <div class="box-body boxpad">
                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Ticket ID</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo $model->mop->ticketId;?>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Opened Date</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo $model->mop->openDate;?>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">MOP Name</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo $model->mop->MOPName;?>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">MOP Customer Shared Date</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo $model->mop->MOPCusSharedDate;?>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Operator</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo @$model->operatorsName->operatorName;?>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Issue Description</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo $model->mop->issueDescription;?>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Solution</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo $model->mop->solution;?>
                                                </div>
                                            </div>
                                        </div>
										<div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">MOP Creator</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo @$model->mop->creatorsName->firstname;?>
                                                </div>
                                            </div>
                                        </div>
										<div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Technical Approval</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo $model->mop->techApproval;?>
                                                </div>
                                            </div>
                                        </div>
										<div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Approve By</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo @$model->mop->approverName->firstname;?>
                                                </div>
                                            </div>
                                        </div>
					                   <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Activity Schedule Date</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo @$model->scheduleactivity->scheduleTimeSL;?>
                                                </div>
                                            </div>
                                        </div>
					                   <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Approve Comments</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                    <?php echo @$model->mop->approveComment;?>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Link to MOP</label>
                                                <div class="col-sm-8 detail-view-padding" >
                                                 <a href="<?= $model->mop->linkToMOP;?>" target="_blank"><?php echo $model->mop->linkToMOP;?>
                                                 </a>  
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div> 
                            <!-- </form>  -->                                                      
                        </div>
                        
                        <div class="modal-footer">
                            <?= Html::button('Close', ['class' => 'btn btn-default', 'name' => 'closeView', 'id' => 'closeMopView']) ?>
                        </div>
                        <?php ActiveForm::end() ?>
<?php
$script = <<< JS
$( document ).ready(function() {
       
        $('#closeMopView').click(function() {
             window.parent.closeMopViewModal();
         });  
    });
JS;

$this->registerJs($script);
?>