models/Rca.php
<?php

namespace app\models;

use Yii;
use app\models\Ticketinfo;
use app\models\RcaSearch;

/**
 * This is the model class for table "rca".
 *
 * @property int $rcaId
 * @property int $ticketId
 * @property string $openDate
 * @property string $sharedDate
 * @property string $RCAName
 * @property string $operator
 * @property string $issueDescription
 * @property string $RCACreator
 * @property string $linkToRCA
 */
class Rca extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */

    const SCENARIO_SRH_STR = 'srh_str';
    const SCENARIO_SRH_EN = 'srh_en';
    const SCENARIO_SRH_ID = 'srh_id';
    const SCENARIO_SRH_OPR = 'srh_opr';
    const SCENARIO_SRH_CTR = 'srh_ctr';

    const SCENARIO_DIST_RCA = 'dist_rca';

    public $start;
    public $end;
    public $id;
    public $operatorName;
    public $creator;
    public $startDate;
    public $endDate;
    public $filter;

    public static function tableName()
    {
        return 'rca';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [

            [['start'], 'required', 'on' => [self::SCENARIO_SRH_STR]],

            [['end'], 'required', 'on' => [self::SCENARIO_SRH_EN]],

            [['id'], 'required', 'on' => [self::SCENARIO_SRH_ID]],

            [['operatorName'], 'required', 'on' => [self::SCENARIO_SRH_OPR]],

           // [['creator'], 'required', 'on' => [self::SCENARIO_SRH_CTR]],

	    [['startDate','endDate','filter'], 'required', 'on' => [self::SCENARIO_DIST_RCA]],

            [['ticketId', 'openDate', 'RCAName', 'operator', 'issueDescription', /*'RCACreator',*/ 'linkToRCA'], 'required'],

            [['ticketId'], 'integer'],

            //[['ticketId'], 'validateticketId'],

            [['openDate', 'sharedDate'], 'safe'],

            [['RCAName', 'issueDescription', 'linkToRCA'], 'string', 'max' => 500],

            [['operator'], 'string', 'max' => 200],

            [['RCACreator'], 'string', 'max' => 100],

	    [['ticketId', 'RCAName'], 'unique', 'targetAttribute' => ['ticketId', 'RCAName']],

	    ['ticketId','match','pattern'=>'/^((?!(0))[0-9]{4,5}$)/'],

	    ['RCAName','match','pattern'=>'/^(RCA)(\_)([A-Z][(A-Z)(a-z)\-]+)(\_)((?!(0))[0-9]{4,5})(\_)([A-Z][a-z\-]+)(\_)(([0-2][0-9]|(3)[0-1])(((0)[0-9])|((1)[0-2]))\d{4})(\_)([v][1-9]$)/'],

	    /*['RCAName','match','pattern'=>'/^(RCA)(\_)(Tigo-Bolivia|Millicom-Tanzania|Hutch-SriLanka|Etisalat-SriLanka|Telecom-SriLanka|Airtel-SriLanka|Ooredoo-Maldives|IAF:ALU-India|TATA-India|DTAC-Thailand|TrueMove-Thailand|Millicom-Ghana|Vini-Tahiti|Millicom-Chad|Millicom-Senagal|Safaricom-Kenya|Vodafone-New Zealand|Tigo-Honduras|Intelli-Australia|Tigo-Colombia|Cellcard-Cambodia|Tigo-ElSalvador|Tigo-Paraguay|Smart-Cambodia|Laogw-Laos)(\_)((?!(0))[0-9]{4,5})(\_)([A-Z][a-z\-]+)(\_)(([0-2][0-9]|(3)[0-1])(((0)[0-9])|((1)[0-2]))\d{4})(\_)([v][1-9]$)/'],*/

        ];
    }

    

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'rcaId' => 'Rca ID',
            'ticketId' => 'Ticket ID',
            'openDate' => 'Open Date',
            'sharedDate' => 'Shared Date',
            'RCAName' => 'Rcaname',
            'operator' => 'Operator',
            'issueDescription' => 'Issue Description',
            'RCACreator' => 'Rcacreator',
            'linkToRCA' => 'Link To Rca',
        ];
    }

    public function getOperatorsName(){
        
        return $this->hasOne(Operator::className(),['operatorId'=>'operator']);

    }

    public function getCreatorsName(){
         return $this->hasOne(User::className(),['id'=>'RCACreator']);
       //Pxx return $this->hasOne(Creator::className(),['createrId'=>'RCACreator']);

    }

    
}

controllers/RcaController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\NotFoundHttpException;
use app\models\Rca;
use app\models\RcaSearch;
use app\controllers\AppController;
use app\models\createform;
use yii\helpers\Url;
$session = Yii::$app->session;
$username = $session['user_name'];
$firstname = $session['first_name'];

class RcaController extends Controller
{
    /**
     * {@inheritdoc}
     */
    
   public function behaviors()
    {
        return [
            
    
        ];
    }

    public function beforeAction($action) 
    {
        $this->enableCsrfValidation = false;
        
        return parent::beforeAction($action);
    }

    public function actionRcaoperation()
    {
        
        $searchModel = new RcaSearch();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('rcaoperation', ['searchModel'=>$searchModel,'dataProvider' => $dataProvider]);


    }

    public function actionCreate(){

        $this->layout = 'popup';

        $model = new Rca();
        
        if ($model->load(Yii::$app->request->post()) ) {
            //$model->RCACreator=Yii::$app->user->identity->id;
            //if( $model->save()){
                $session = Yii::$app->session;
                $userid = $session['user_id'];
                $model->RCACreator=(string)$userid;
                $model->save();
                Yii::$app->readWriteLog->readWriteLog("app\models\Rca RCA Record created successfully",['TicketId'=>$model->ticketId,'RCA Name'=>$model->RCAName,'RCA Creator'=>$model->creatorsName->firstname],2);

                return $this->render('createform',['model' => $model]);
           // }
	   

        } else{

            return $this->render('createform',['model' => $model]);
        }
    }

    public function actionView($id)
    {
        $this->layout = 'popup';

        $model = Rca::findOne($id);

        return $this->render('viewform',['model'=> $model]);
    
    }

    public function actionUpdate($id){

        $this->layout = 'popup';

        $model = Rca::findOne($id);

    if($model->load(Yii::$app->request->post()) && $model->save()){

	Yii::$app->readWriteLog->readWriteLog("app\models\Rca RCA Record updated successfully",['TicketId'=>$model->ticketId,'RCA Name'=>$model->RCAName,'RCA Creator'=>$model->creatorsName->firstname],2);

        return $this->render('updateform',['model'=>$model]);

    }
    else{
        return $this->render('updateform',['model'=>$model]);
    }

    }

   public function actionDelete($id)
    {
        
        $model = Rca::findOne($id);

        if ($model->delete()){

	Yii::$app->readWriteLog->readWriteLog("app\models\Rca RCA Record deleted",['Ticket ID'=>$model->ticketId,'RCA Name'=>$model->RCAName],2);

        return $this->redirect(['rcaoperation']);

        }

        
    }

    public function actionRcadistribution()
    {
  
        $model = new rca();

        return $this->render('rcadistribution', ['model'=>$model]);
    }
       
    public function actionShowrcadistribution()
    {

        $model = new rca();
        
        $model->scenario = rca::SCENARIO_DIST_RCA;
      
         if (Yii::$app->request->isPost) 
        {

            $model->load(Yii::$app->request->post());

            $smonth = \yii\helpers\ArrayHelper::getValue($_POST, 'startDate');
            $emonth = \yii\helpers\ArrayHelper::getValue($_POST, 'endDate');
            $filter = \yii\helpers\ArrayHelper::getValue($_POST, 'filter');

            /*echo $smonth;
            echo $emonth;
            echo $filter;
            exit;*/
            $sql="SELECT ";

            /*$sql="SELECT DATE_FORMAT(openDate,'%Y-%M') AS Month,COUNT(rcaId) AS Count from rca WHERE DATE_FORMAT(openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' GROUP BY Month";

            echo $sql;
            exit;*/

            if ($filter=='')
                    $sql .= "DATE_FORMAT(openDate,'%Y-%M') AS Category,COUNT(rcaId) AS Count from rca WHERE DATE_FORMAT(openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' GROUP BY Category";

            if ($filter=='Month')
                    $sql .= "DATE_FORMAT(openDate,'%Y-%M') AS Category,COUNT(rcaId) AS Count from rca WHERE DATE_FORMAT(openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' GROUP BY Category";

            if ($filter=='operator')
                    $sql .= "o.operatorName AS Category,COUNT(r.rcaId) AS Count from rca r, operator o WHERE DATE_FORMAT(r.openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' and r.operator = o.operatorId GROUP BY r.operator";

	    if ($filter=='RCACreator')
                    //Pxx $sql .= "c.createrName AS Category,COUNT(r.rcaId) AS Count from rca r, creator c WHERE DATE_FORMAT(r.openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' and r.RCACreator = c.createrId GROUP BY r.RCACreator";
                     $sql .= "c.firstname AS Category,COUNT(r.rcaId) AS Count from rca r, user c WHERE DATE_FORMAT(r.openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' and r.RCACreator = c.id GROUP BY r.RCACreator";
            $connection = Yii::$app->getDb();
            try {
                
                $result = $connection->createCommand($sql)->queryAll();

                $data = array();
                    foreach ($result as $row) {
                    $data[] = $row;
                }

                //$data=array_reverse($data);

                print json_encode($data);
                
                exit;

                } catch (Exception $e) {
            }
        }

    }

    
}

views/rca/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RcaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rca-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'rcaId') ?>

    <?= $form->field($model, 'ticketId') ?>

    <?= $form->field($model, 'openDate') ?>

    <?= $form->field($model, 'sharedDate') ?>

    <?= $form->field($model, 'RCAName') ?>

    <?php // echo $form->field($model, 'operator') ?>

    <?php // echo $form->field($model, 'issueDescription') ?>

    <?php // echo $form->field($model, 'RCACreator') ?>

    <?php // echo $form->field($model, 'linkToRCA') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/rca/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RcaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Rcas');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rca-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Rca'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'rcaId',
            'ticketId',
            'openDate',
            'sharedDate',
            'RCAName',
            //'operator',
            //'issueDescription',
            //'RCACreator',
            //'linkToRCA',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/rca/rcadistribution.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\helpers\Url;
use kartik\date\DatePicker;
use kartik\select2\Select2;

$this->title = 'Operations Assistance Portal | Wavenet';

?>
<!-- Content Header (Page header) -->
			<section class="content-header">
				<h1>
					Root Cause Analysis
					<small>Distribution Graphs </small>
				</h1>
				<ol class="breadcrumb">
					<li><i class="fa fa-dashboard"></i> Dashboard</li>
					<li><i class="fa fa-laptop"></i> Resolution and Activities</li>
                    <li><i class=""></i> RCA</li>
					<li class="active">RCA Distribution</li>
				</ol>
			</section>

			<!-- Main content -->
			<section class="content">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="box">
                            <div class="box-header with-border">
								<h3 class="box-title">Filters</h3>
							</div>

							<div class="box-body">
								<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data', 'class'=>'form-horizontal']]) ?>
									<div class="row">
										<div class="box-body boxpad">

                                            <div id="start_datetime-tr" class="col-md-4">
                                                <div class="form-group">
                                                    <label class="col-sm-3 control-label">Start <span
                                                            class="req-fld">*</span>
													</label>
															<?=$form->field($model, 'startDate',['options' => ['class' => 'col-sm-9','id' => 'start']])->label(false)->widget(DatePicker::classname(), ['options' => ['placeholder' => 'YYYY/MM'],
                                                                    'pluginOptions' => [
                                                                        'autoclose' => true,
                                                                        'startView'=>'year',
                                                                        'minViewMode'=>'months',
                                                                        'readonly'=>'true',
                                                                        'format' => 'yyyy-mm'
                                                                        ]
                                                                    ]);?>
                                                </div>
                                            </div>

                                            <div id="start_datetime-tr" class="col-md-4">
                                                <div class="form-group">
                                                    <label class="col-sm-3 control-label">End <span
                                                            class="req-fld">*</span>
													</label>
															<?=$form->field($model, 'endDate',['options' => ['class' => 'col-sm-9','id' => 'end']])->label(false)->widget(DatePicker::classname(), ['options' => ['placeholder' => 'YYYY/MM'],
                                                                    'pluginOptions' => [
                                                                        'autoclose' => true,
                                                                        'startView'=>'year',
                                                                        'minViewMode'=>'months',
                                                                        'readonly'=>'true',
                                                                        'format' => 'yyyy-mm'
                                                                        ]
                                                                    ]);?>
                                                </div>
                                            </div>
                                            <div id="start_datetime-tr" class="col-md-4">
                                                <div class="form-group">
                                                    <label class="col-sm-3 control-label">Filter <span
                                                            class="req-fld">*</span>
                                                    </label>
                                                         <?= $form->field($model, 'filter',['options' => ['class' => 'col-sm-9','id'=>'selector']])->label(false)->widget(Select2::classname(), ['data' => ['Month' => 'Month', 'operator' => 'operator','RCACreator' => 'RCACreator'],'options' => ['placeholder' => 'Filter']]); ?>
                                                    </div>
                                            </div>

										</div>
									</div>
									<div class="row">
										<div class="box-body boxpad">
											<div class="col-md-12 col-sm-12 col-xs-12">
												<div class="box-footer">
														<?= Html::button('Generate Graph', ['class' => 'btn btn-primary pull-right btnspace','name' => 'graph', 'id' => 'graph']) ?>
												</div>
											</div>
										</div>						
									</div>
								<?php ActiveForm::end() ?>
							</div>
						</div>
					</div>
				</div>

				<div id="data_area">
					<div class="row">
						<div class="col-md-12">
							<div class="box">
								<div class="box-header with-border">
									<h3 class="box-title">RCA Distribution Graph</h3>
								</div>
								<div class="box-body">
									<canvas id="mycanvas"></canvas>
								</div>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-md-12 col-sm-12 col-xs-12">
							<div class="box">
								<div class="box-header with-border">
									<h3 class="box-title">Report Data</h3>
								</div>
								<div class="box-body">
									<form class="form-horizontal" name="form_blacklist_table" id="">
										<div class="row">
											<div class="box-body boxpad contSeperator">
												<div id='table-parent' class="col-md-12 col-sm-12 col-xs-12" style="overflow:scroll;width:100%;overflow:auto">
													<table id="table" class="table table-bordered table-striped table-hover">
													</table>
												</div>
											</div>						
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>

				</div>
                
			
			</section>
			<!-- /.content -->
<?php
$url = Url::to(['rca/showrcadistribution']);
//echo $url;
$script = <<< JS
    $(document).ready(function(){
    
    $('#graph').bind("click", function () {
        

          $.ajax({
            url : "{$url}",
            type : "POST",
            data: {  startDate: $('#rca-startdate').val(), endDate: $('#rca-enddate').val(), filter: $('#rca-filter').val()},
            success : function(data){
            console.log(data);
            var data = JSON.parse(data);

            var Category = [];
            var Count = [];

            for(var i in data) {
                Category.push(data[i].Category);
                Count.push(parseInt(data[i].Count));
              } 

              var chartdata = {
              labels: Category,
              datasets: [
                  {
                    label: "RCA Count",
                    fill: false,
                    lineTension: 0.1,
                    backgroundColor: "rgba(54, 162, 235, 0.8)",
                    borderColor: "rgba(54, 162, 235, 1)",
                    pointHoverBackgroundColor: "rgba(54, 162, 235, 1)",
                    pointHoverBorderColor: "rgba(54, 162, 235, 1)",
                    borderWidth: 1,
                    data: Count
                  }
                ]
              };

              var ctx = $("#mycanvas");

              if(window.bar != undefined)
                
                window.bar.destroy();

              window.bar = new Chart(ctx, {
                type: 'bar',
                data: chartdata,
                options: {
                    scales: {
                        xAxes: [{
                            display: true,
                            scaleLabel: {
                            display: true,
                            labelString: 'Category'
                        }
                    }],
                        yAxes: [{
                            display: true,
                            scaleLabel: {
                            display: true,
                            labelString: 'RCA Count'
                        },
                        ticks: {
                            beginAtZero:true
                        }
                    }]
                }
            
                }
              });

             document.getElementById("table").innerHTML = "";
        
            var col = [];
            for (var i = 0; i < data.length; i++) {
                for (var key in data[i]) {
                    if (col.indexOf(key) === -1) {
                        col.push(key);
                    }
                }
            }
        
            var table = document.getElementById("table");

            var tr = table.insertRow(-1); 

            for (var i = 0; i < col.length; i++) {
                var th = document.createElement("th"); 
                th.innerHTML = col[i];
                tr.appendChild(th);
            }

    
            for (var i = 0; i < data.length; i++) {
                tr = table.insertRow(-1);

                for (var j = 0; j < col.length; j++) {
                    var tabCell = tr.insertCell(-1);
                    tabCell.innerHTML = data[i][col[j]];
                }
            }

            var tr = table.insertRow(-1); 
            var td = document.createElement("td");
            td.innerHTML = "Total";
            tr.appendChild(td);

            for (var j = 1; j < col.length; j++) {

                sum = 0;    

                for (var i = 0; i < data.length; i++) {

                    var td = document.createElement("td");
                    var sum = parseInt(sum) + parseInt(data[i][col[j]]);
                }
                    td.innerHTML = sum;
                    tr.appendChild(td);
            }
            
            $("#table-parent").append(table);

        
            },

        error : function(data) {

        }

          });
    });     
    

});

JS;

$this->registerJs($script);
?>

  

views/rca/updateform.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Rca */
/* @var $form yii\widgets\ActiveForm */
?>                    
                    <div class="modal-body">
                            <!-- <form class="form-horizontal"> -->
                            <?php $form = ActiveForm::begin(['options' => ['id' => 'Update-form','class'=>'form-horizontal']]) ?>
                                <div class="row">
                                    <div class="box-body boxpad">

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Ticket ID</label>
                                                <div class="col-sm-8" >
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->ticketId;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Opened Date</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->openDate;?>'>      
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">RCA Name</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->RCAName;?>'>
                                                     </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">RCA Shared Date</label>
                                                <!-- <div class="col-sm-8"> -->
                                                    <?=$form->field($model, 'sharedDate',['options' => ['class' => 'col-sm-8','id' => 'sharedDate']])->label(false)->widget(DatePicker::classname(), ['options' => ['placeholder' => 'YYYY/MM/DD'],
                                                            'pluginOptions' => [
                                                                'autoclose' => true,
                                                                'format' => 'yyyy-mm-dd'
                                                            ]
                                                        ]);?>
                                                <!-- </div> -->
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Operator</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->operatorsName->operatorName;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">RCA Creator</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->creatorsName->firstname;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Link to RCA</label>
                                                <!-- <div class="col-sm-8"> -->
                                                    <?= $form->field($model, 'linkToRCA',['options' => ['class' => 'col-sm-8']])->textInput(['maxlength' => true,'placeholder' => 'URL','title' => $model->linkToRCA])->label(false);?>
                                                <!-- </div> -->
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Issue Description</label>
                                                <!-- <div class="col-sm-8"> -->
                                                    <?= $form->field($model, 'issueDescription',['options' => ['class' => 'col-sm-8']])->textarea(['rows' => '3','maxlength' => true,'placeholder' => 'Description'])->label(false);?>
                                                <!-- </div> -->
                                            </div>
                                        </div>

                                    </div>
                                </div> 
                            <!-- </form> -->                                                       
                        </div>

                        <div class="modal-footer">
                            <!--?= Html::button('Close', ['class' => 'btn btn-default','name' => 'closeUpdate', 'id' => 'closeUpdate']) ?-->
                            <?= Html::submitButton('Save Changes', ['class' => 'btn btn-primary','name' => 'update', 'id' => 'update']) ?>
                        </div>
                        <?php ActiveForm::end() ?>
<?php
$script = <<< JS
$( document ).ready(function() {
       
        $('#closeUpdate').click(function() {
             window.parent.closeUpdateModal();
         });  
    });
JS;

$this->registerJs($script);
?>