models/Ticketinfo.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "ticketinfo".
 *
 * @property int $ticketId
 * @property string $subject
 * @property string $status
 * @property string $priority
 * @property string $source
 * @property string $type
 * @property string $agent
 * @property string $groupName
 * @property string $createTime
 * @property string $dueTime
 * @property string $resolveTime
 * @property string $closeTime
 * @property string $lastUpdateTime
 * @property string $initialResponseTime
 * @property string $timeTracked
 * @property string $firstResponseTime
 * @property string $resolutionTime
 * @property int $agentInt
 * @property int $cusInt
 * @property string $resolutionstatus
 * @property string $responseStatus
 * @property string $tags
 * @property string $surveyResult
 * @property string $internalAgent
 * @property string $product
 * @property string $internalGroup
 * @property string $effectiveFirstResponse
 * @property string $mgmtEscalated
 * @property string $acknowledger
 * @property string $productName
 * @property string $severity
 * @property string $operator
 * @property string $issueCategory
 * @property string $workingTimeOfDay
 * @property string $neutralize
 * @property string $resolution
 * @property string $fullName
 * @property string $title
 * @property string $email
 * @property string $workPhone
 * @property string $mobilePhone
 * @property string $twitterId
 * @property string $timezone
 * @property string $language
 * @property string $uniqueExternal
 * @property string $facebook
 * @property string $contactId
 * @property string $companyName
 * @property string $companyDomain
 * @property string $healthScore
 * @property string $accountTier
 * @property string $AMCPeriodStart
 * @property string $AMCPeriodEnd
 * @property string $renewalDate
 * @property string $SLAStatus
 * @property string $SLACusContact
 * @property string $industry
 * @property string $resolutionSummary
 * @property string $escalationSummary
 * @property int $outage_time
 */
class Ticketinfo extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ticketinfo';
    }

    const SCENARIO_DIST = 'scn_dist';

    public $date;
    public $start;
    public $end;
    public $region;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [

            [['date','start','end','region'], 'required', 'on' => [self::SCENARIO_DIST]],

            [['ticketId'], 'required'],

            [['ticketId', 'agentInt', 'cusInt'], 'integer'],

            [['createTime', 'dueTime', 'resolveTime', 'closeTime', 'lastUpdateTime', 'initialResponseTime', 'timeTracked', 'firstResponseTime', 'resolutionTime', 'AMCPeriodStart', 'AMCPeriodEnd', 'renewalDate'], 'safe'],

            [['subject', 'internalAgent', 'internalGroup', 'fullName', 'email', 'industry'], 'string', 'max' => 200],

            [['status', 'priority', 'type', 'groupName', 'product', 'effectiveFirstResponse', 'mgmtEscalated', 'productName', 'severity', 'operator', 'issueCategory', 'workingTimeOfDay', 'neutralize', 'resolution', 'workPhone', 'mobilePhone', 'twitterId', 'timezone', 'language', 'facebook', 'contactId', 'companyDomain', 'healthScore', 'accountTier', 'SLAStatus', 'resolutionSummary', 'escalationSummary'], 'string', 'max' => 50],

            [['source', 'resolutionstatus', 'responseStatus', 'tags', 'surveyResult', 'title'], 'string', 'max' => 20],

            [['agent', 'acknowledger', 'uniqueExternal', 'companyName', 'SLACusContact'], 'string', 'max' => 100],

            [['ticketId'], 'unique'],
            
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'ticketId' => 'Ticket ID',
            'subject' => 'Subject',
            'status' => 'Status',
            'priority' => 'Priority',
            'source' => 'Source',
            'type' => 'Type',
            'agent' => 'Agent',
            'groupName' => 'Group Name',
            'createTime' => 'Create Time',
            'dueTime' => 'Due Time',
            'resolveTime' => 'Resolve Time',
            'closeTime' => 'Close Time',
            'lastUpdateTime' => 'Last Update Time',
            'initialResponseTime' => 'Initial Response Time',
            'timeTracked' => 'Time Tracked',
            'firstResponseTime' => 'First Response Time',
            'resolutionTime' => 'Resolution Time',
            'agentInt' => 'Agent Int',
            'cusInt' => 'Cus Int',
            'resolutionstatus' => 'Resolutionstatus',
            'responseStatus' => 'Response Status',
            'tags' => 'Tags',
            'surveyResult' => 'Survey Result',
            'internalAgent' => 'Internal Agent',
            'product' => 'Product',
            'internalGroup' => 'Internal Group',
            'effectiveFirstResponse' => 'Effective First Response',
            'mgmtEscalated' => 'Mgmt Escalated',
            'acknowledger' => 'Acknowledger',
            'productName' => 'Product Name',
            'severity' => 'Severity',
            'operator' => 'Operator',
            'issueCategory' => 'Issue Category',
            'workingTimeOfDay' => 'Working Time Of Day',
            'neutralize' => 'Neutralize',
            'resolution' => 'Resolution',
            'fullName' => 'Full Name',
            'title' => 'Title',
            'email' => 'Email',
            'workPhone' => 'Work Phone',
            'mobilePhone' => 'Mobile Phone',
            'twitterId' => 'Twitter ID',
            'timezone' => 'Timezone',
            'language' => 'Language',
            'uniqueExternal' => 'Unique External',
            'facebook' => 'Facebook',
            'contactId' => 'Contact ID',
            'companyName' => 'Company Name',
            'companyDomain' => 'Company Domain',
            'healthScore' => 'Health Score',
            'accountTier' => 'Account Tier',
            'AMCPeriodStart' => 'Amcperiod Start',
            'AMCPeriodEnd' => 'Amcperiod End',
            'renewalDate' => 'Renewal Date',
            'SLAStatus' => 'Slastatus',
            'SLACusContact' => 'Slacus Contact',
            'industry' => 'Industry',
	    'resolutionSummary' => 'Resolution Summary',
            'escalationSummary' => 'Escalation Summary',
	    'outage_time' =>'Outage Time',
        ];
    }
}

controllers/TicketinfoController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\UploadedFile;
use yii\web\NotFoundHttpException;
use app\models\Ticketinfo;
use yii\data\SqlDataProvider;
use yii\helpers\Json;
use app\controllers\AppController;
use yii\data\ArrayDataProvider;
use yii\helpers\BaseArrayHelper;


class TicketinfoController extends Controller
{
    /**
     * {@inheritdoc}
     */

    // public function behaviors()
    // {
    //     return [
            
    
    //     ];
    // }
    public function beforeAction($action) 
    {
		$this->enableCsrfValidation = false;
		
		return parent::beforeAction($action);
	}
   
    public function actionLeveldistribution()
    {

   		$model = new Ticketinfo();

    	return $this->render('Leveldistribution', ['model'=>$model]);

	}

	public function actionShowleveldistribution()
    {

    	$model = new Ticketinfo();
    	$model->scenario = Ticketinfo::SCENARIO_DIST;

    	 if (Yii::$app->request->isPost) 
        {

            $model->load(Yii::$app->request->post());
            $month = \yii\helpers\ArrayHelper::getValue($_POST, 'date');
            $dregion = \yii\helpers\ArrayHelper::getValue($_POST, 'region');
            if ($dregion == '')
                $sql="SELECT SUBSTRING(groupName, 1,(CHAR_LENGTH(groupName) - 3)) AS level, SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L1' THEN 1 ELSE 0 END) AS L1,SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L2' THEN 1 ELSE 0 END) AS L2, SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L3' THEN 1 ELSE 0 END) AS L3,SUM((CASE WHEN SUBSTRING(groupName, -2, 2) = 'L1' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L2' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L3' THEN 1 ELSE 0 END)) AS Total FROM `ticketinfo` WHERE DATE_FORMAT(createTime,'%Y-%m')='$month' AND SUBSTRING(groupName, 1,(CHAR_LENGTH(groupName) - 3)) IN('Latam', 'East Asia','Asia') GROUP BY level";
            if ($dregion == 'Latam')
                $sql="SELECT SUBSTRING(groupName, 1,(CHAR_LENGTH(groupName) - 3)) AS level, SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L1' THEN 1 ELSE 0 END) AS L1,SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L2' THEN 1 ELSE 0 END) AS L2, SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L3' THEN 1 ELSE 0 END) AS L3,SUM((CASE WHEN SUBSTRING(groupName, -2, 2) = 'L1' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L2' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L3' THEN 1 ELSE 0 END)) AS Total FROM `ticketinfo` WHERE DATE_FORMAT(createTime,'%Y-%m')='$month' AND SUBSTRING(groupName, 1,(CHAR_LENGTH(groupName) - 3)) IN('Latam', 'East Asia','Asia') AND groupName like 'Latam%' GROUP BY level";
            if ($dregion == 'Asia')
                $sql="SELECT SUBSTRING(groupName, 1,(CHAR_LENGTH(groupName) - 3)) AS level, SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L1' THEN 1 ELSE 0 END) AS L1,SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L2' THEN 1 ELSE 0 END) AS L2, SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L3' THEN 1 ELSE 0 END) AS L3,SUM((CASE WHEN SUBSTRING(groupName, -2, 2) = 'L1' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L2' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L3' THEN 1 ELSE 0 END)) AS Total FROM `ticketinfo` WHERE DATE_FORMAT(createTime,'%Y-%m')='$month' AND SUBSTRING(groupName, 1,(CHAR_LENGTH(groupName) - 3)) IN('Latam', 'East Asia','Asia') AND groupName like 'Asia%' GROUP BY level";
            if ($dregion == 'SEA')
                $sql="SELECT SUBSTRING(groupName, 1,(CHAR_LENGTH(groupName) - 3)) AS level, SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L1' THEN 1 ELSE 0 END) AS L1,SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L2' THEN 1 ELSE 0 END) AS L2, SUM(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L3' THEN 1 ELSE 0 END) AS L3,SUM((CASE WHEN SUBSTRING(groupName, -2, 2) = 'L1' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L2' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(groupName, -2, 2) = 'L3' THEN 1 ELSE 0 END)) AS Total FROM `ticketinfo` WHERE DATE_FORMAT(createTime,'%Y-%m')='$month' AND SUBSTRING(groupName, 1,(CHAR_LENGTH(groupName) - 3)) IN('Latam', 'East Asia','Asia') AND groupName like 'East Asia%'GROUP BY level";
           
           	$connection = Yii::$app->getDb();
         
            try {
                
                $result = $connection->createCommand($sql)->queryAll();

                $data = array();
					foreach ($result as $row) {
  					$data[] = $row;
				}

                print json_encode($data);
                
                exit;

                } catch (Exception $e) {
            }
        }

	}

	public function actionWorkingtimedistribution()
    {

   		$model = new Ticketinfo();

    	return $this->render('Workingtimedistribution', ['model'=>$model]);

	}

	public function actionShowworkingtimedistribution()
    {

    	$model = new Ticketinfo();
    	
    	$model->scenario = Ticketinfo::SCENARIO_DIST;

    	 if (Yii::$app->request->isPost) 
        {

            $model->load(Yii::$app->request->post());

            $month = \yii\helpers\ArrayHelper::getValue($_POST, 'date');

            //$sql="SELECT severity AS severity, SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END) AS 'Office', SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END) AS 'Out',SUM((CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END)) AS Total from `ticketinfo` WHERE DATE_FORMAT(createTime,'%Y-%m')='$month' AND severity IN ('Major', 'Minor','Critical') GROUP BY severity";
            $dregion = \yii\helpers\ArrayHelper::getValue($_POST, 'region');
            $sql="SELECT severity AS severity, SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END) AS 'Office', SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END) AS 'Out',SUM((CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END)) AS Total from `ticketinfo` WHERE DATE_FORMAT(createTime,'%Y-%m')='$month' AND severity IN ('Major', 'Minor','Critical') GROUP BY severity";
           
            if ($dregion == '')
                $sql="SELECT severity AS severity, SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END) AS 'Office', SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END) AS 'Out',SUM((CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END)) AS Total from `ticketinfo` WHERE DATE_FORMAT(createTime,'%Y-%m')='$month' AND severity IN ('Major', 'Minor','Critical') GROUP BY severity";
            if ($dregion == 'Latam')
                $sql="SELECT severity AS severity, SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END) AS 'Office', SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END) AS 'Out',SUM((CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END)) AS Total from `ticketinfo` WHERE DATE_FORMAT(createTime,'%Y-%m')='$month' AND severity IN ('Major', 'Minor','Critical') AND groupName like 'Latam%' GROUP BY severity";
            if ($dregion == 'Asia')
                $sql="SELECT severity AS severity, SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END) AS 'Office', SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END) AS 'Out',SUM((CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END)) AS Total from `ticketinfo` WHERE DATE_FORMAT(createTime,'%Y-%m')='$month' AND severity IN ('Major', 'Minor','Critical') AND groupName like 'Asia%' GROUP BY severity";
            if ($dregion == 'SEA')
                $sql="SELECT severity AS severity, SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END) AS 'Office', SUM(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END) AS 'Out',SUM((CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '8am to 6pm' THEN 1 ELSE 0 END)+(CASE WHEN SUBSTRING(workingTimeOfDay, -11, 10)= '6pm to 8am' THEN 1 ELSE 0 END)) AS Total from `ticketinfo` WHERE DATE_FORMAT(createTime,'%Y-%m')='$month' AND severity IN ('Major', 'Minor','Critical') AND groupName like 'East Asia%' GROUP BY severity";
            
           	$connection = Yii::$app->getDb();
         
            try {
                
                $result = $connection->createCommand($sql)->queryAll();

                $data = array();
					foreach ($result as $row) {
  					$data[] = $row;
				}

                print json_encode($data);
                
                exit;

                } catch (Exception $e) {
            }
        }

	}

    	public function actionProductdistribution()
    {

        $model = new Ticketinfo();

        return $this->render('Productdistribution', ['model'=>$model]);

    }

    public function actionShowproductdistribution()
    {

        $model = new Ticketinfo();
        $model->scenario = Ticketinfo::SCENARIO_DIST;

         if (Yii::$app->request->isPost) 
        {

            $model->load(Yii::$app->request->post());

            $month = \yii\helpers\ArrayHelper::getValue($_POST, 'date');

views/ticketinfo/Leveldistribution.php
<?php

//use dosamigos\datepicker\DatePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\helpers\Url;
use kartik\date\DatePicker;
use kartik\select2\Select2;

$this->title = 'Operations Assistance Portal | Wavenet';

?>
<!-- Content Header (Page header) -->
			<section class="content-header">
				<h1>
					Level wise
					<small>Monthly Reports (Tickets)</small>
				</h1>
				<ol class="breadcrumb">
					<li><i class="fa fa-dashboard"></i> Dashboard</li>
					<li><i class="fa fa-laptop"></i> Performance</li>
                    <li><i class=""></i> Monthly Reports (Tickets)</li>
					<li class="active">Level wise</li>
				</ol>
			</section>

			<!-- Main content -->
			<section class="content">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="box">
                            <div class="box-header with-border">
								<h3 class="box-title">Filters - Month</h3>
							</div>

							<div class="box-body">
								<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data', 'class'=>'form-horizontal']]) ?>
									<div class="row">
										<div class="box-body boxpad">
											<div id="start_datetime-tr" class="col-md-6">
													<div class="form-group">
															<label class="col-sm-4 control-label">Month <span
																class="req-fld">*</span>
															</label>
															<?=$form->field($model, 'date',['options' => ['class' => 'col-sm-8','id' => 'date']])->label(false)->widget(DatePicker::classname(), ['options' => ['placeholder' => 'YYYY/MM','data-toggle' => 'tooltip','data-placement'=>'bottom','title'=>'Ticket Creation Date'],
																'pluginOptions' => [
																	'autoclose' => true,
																	'startView'=>'year',
																	'minViewMode'=>'months',
																	'format' => 'yyyy-mm'
																	]
																]);?>
													</div>
											</div>
											<div id="start_datetime-tr" class="col-md-4">
                                                <div class="form-group">
                                                    <label class="col-sm-3 control-label">Region <span
                                                            class="req-fld">*</span>
                                                    </label>
                                                         <?= $form->field($model, 'region',['options' => ['class' => 'col-sm-9','id'=>'region']])->label(false)->widget(Select2::classname(), ['data' => ['Latam' => 'Latam', 'Asia' => 'Asia','SEA' => 'SEA'],'options' => ['placeholder' => 'Region'],'pluginOptions' => ['allowClear' => true]]); ?>
                                                    </div>
                                            </div>
										</div>
									</div>
									<div class="row">
										<div class="box-body boxpad">
											<div class="col-md-12 col-sm-12 col-xs-12">
												<div class="box-footer">
														<?= Html::button('Generate Graph', ['class' => 'btn btn-primary pull-right btnspace','name' => 'graph', 'id' => 'graph']) ?>
												</div>
											</div>
										</div>						
									</div>
								<?php ActiveForm::end() ?>
							</div>
						</div>
					</div>
				</div>
			<div id="data_area">
        <div class="row">
					<div class="col-md-12">
						<div class="box">
							<div class="box-header with-border">
								<h3 class="box-title">Distribution Graph</h3>
							</div>
							<div class="box-body">
								<canvas id="mycanvas"></canvas>
							</div>
						</div>
					</div>
                </div>
						<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="box">
							<div class="box-header with-border">
								<h3 class="box-title">Report Data</h3>
							</div>
							<div class="box-body">
								<form class="form-horizontal" name="form_blacklist_table" id="">
									<div class="row">
										<div class="box-body boxpad contSeperator">
											<div id='table-parent' class="col-md-12 col-sm-12 col-xs-12">
												<table id="table" class="table table-bordered table-striped table-hover"></table>
											</div>
										</div>						
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			</section>
			<!-- /.content -->
<?php
$url = Url::to(['ticketinfo/showleveldistribution']);
//echo $url;
$script = <<< JS
	$("#graph").click(function() {
    $('html, body').animate({
        scrollTop: $("#data_area").offset().top
    }, 1000);
    });
	$(document).ready(function(){
	
	$('#graph').bind("click", function () {
		

		  $.ajax({
			url : "{$url}",
			type : "POST",
			data: { date: $('#ticketinfo-date').val(), region: $('#ticketinfo-region').val()},
			success : function(data){
			console.log(data);
			var data = JSON.parse(data);

			  var level = [];
			  var L1 = [];
			  var L2 = [];
			  var L3 = [];
			  var Total = [];

			  for(var i in data) {
				level.push(data[i].level);
				L1.push(parseInt(data[i].L1));
				L2.push(parseInt(data[i].L2));
				L3.push(parseInt(data[i].L3));
				Total.push(parseInt(data[i].Total));
			  }		 

			  var chartdata = {
			  labels: level,
			  datasets: [
				  {
					label: "L1",
					fill: false,
					lineTension: 0.1,
					backgroundColor: "rgba(54, 162, 235, 0.8)",
					borderColor: "rgba(54, 162, 235, 1)",
					pointHoverBackgroundColor: "rgba(54, 162, 235, 1)",
					pointHoverBorderColor: "rgba(54, 162, 235, 1)",
					borderWidth: 1,
					data: L1
				  },
				  {
					label: "L2",
					fill: false,
					lineTension: 0.1,
					backgroundColor: "rgba(255, 99, 132, 0.8)",
					borderColor: "rgba(255, 99, 132,1)",
					pointHoverBackgroundColor: "rgba(255, 99, 132,1)",
					pointHoverBorderColor: "rgba(255, 99, 132,1)",
					borderWidth: 1,
					data: L2
				  },
				  {
					label: "L3",
					fill: false,
					lineTension: 0.1,
					backgroundColor: "rgba(255, 206, 86, 0.8)",
					borderColor: "rgba(255, 206, 86, 1)",
					pointHoverBackgroundColor: "rgba(255, 206, 86, 1)",
					pointHoverBorderColor: "rgba(255, 206, 86, 1)",
					borderWidth: 1,
					data: L3
			  }
				]
			  };

			  var ctx = $("#mycanvas");

			  if(window.bar != undefined)
  				
  				window.bar.destroy();

			  window.bar = new Chart(ctx, {
				type: 'bar',
				data: chartdata,
				options: {
        			scales: {
            			xAxes: [{
                			display: true,
                			scaleLabel: {
                    		display: true,
                    		labelString: 'Region'
                		}
            		}],
            			yAxes: [{
                			display: true,
                			scaleLabel: {
                    		display: true,
                    		labelString: 'Ticket Count'
                		},
                		ticks: {
                    		beginAtZero:true
                		}
            		}]
        		}
    		
    			}
			  });

			document.getElementById("table").innerHTML = "";
 		
 	 		var col = [];
        	for (var i = 0; i < data.length; i++) {
            	for (var key in data[i]) {
                	if (col.indexOf(key) === -1) {
                    	col.push(key);
                	}
            	}
        	}
        
			var table = document.getElementById("table");

        	var tr = table.insertRow(-1); 

        	for (var i = 0; i < col.length; i++) {
            	var th = document.createElement("th"); 
            	th.innerHTML = col[i];
            	tr.appendChild(th);
        	}

    
        	for (var i = 0; i < data.length; i++) {
            	tr = table.insertRow(-1);

            	for (var j = 0; j < col.length; j++) {
                	var tabCell = tr.insertCell(-1);
                	tabCell.innerHTML = data[i][col[j]];
            	}
        	}

        	var tr = table.insertRow(-1); 
            var td = document.createElement("td");
            td.innerHTML = "Total";
            tr.appendChild(td);

            for (var j = 1; j < col.length; j++) {

                sum = 0;    

                for (var i = 0; i < data.length; i++) {

                    var td = document.createElement("td");
                    var sum = parseInt(sum) + parseInt(data[i][col[j]]);
                }
                    td.innerHTML = sum;
                    tr.appendChild(td);
            }
    		
    		$("#table-parent").append(table);
        
			},

		error : function(data) {

		}

		  });
	});		
	

});

JS;

$this->registerJs($script);
?>