models/Mop.php
<?php

namespace app\models;

use Yii;
use app\models\Scheduleactivity;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "mop".
 *
 * @property int $mopId
 * @property int $ticketId
 * @property string $openDate
 * @property string $MOPCusSharedDate
 * @property string $MOPCreator
 * @property string $MOPName
 * @property string $operator
 * @property string $issueDescription
 * @property string $solution
 * @property string $linkToMOP
 * @property string $techApproval
 * @property string $techApprovedBy
 * @property int $approvalStatus
 * @property int $approveAlert
 *
 * @property Createactivity[] $createactivities
 */
class Mop extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mop';
    }

    /**
     * {@inheritdoc}
     */
    const SCENARIO_SRH_STR = 'srh_str';
    const SCENARIO_SRH_EN = 'srh_en';
    const SCENARIO_SRH_ID = 'srh_id';
    const SCENARIO_SRH_OPR = 'srh_opr';
    const SCENARIO_SRH_CTR = 'srh_ctr';

    const SCENARIO_DIST_MOP = 'dist_mop';

    public $start;
    public $end;
    public $id;
    public $operatorName;
    public $creator;

    public $startDate;
    public $endDate;
    public $filter;

    public function rules()
    {
        return [

            [['start'], 'required', 'on' => [self::SCENARIO_SRH_STR]],

            [['end'], 'required', 'on' => [self::SCENARIO_SRH_EN]],

            [['id'], 'required', 'on' => [self::SCENARIO_SRH_ID]],

            [['operatorName'], 'required', 'on' => [self::SCENARIO_SRH_OPR]],

           // [['creator'], 'required', 'on' => [self::SCENARIO_SRH_CTR]],

	    [['startDate','endDate','filter'], 'required', 'on' => [self::SCENARIO_DIST_MOP]],

            [['ticketId', 'openDate', 'MOPCreator', 'MOPName', 'operator', 'issueDescription', 'solution', 'linkToMOP','techApprovedBy'], 'required'],

            [['ticketId', 'approvalStatus','approveAlert'], 'integer'],

            [['openDate', 'MOPCusSharedDate'], 'safe'],

            [['MOPCreator'], 'string', 'max' => 100],

            //[['MOPName', 'linkToMOP'], 'string', 'max' => 500],
	    [['MOPName', 'linkToMOP', 'approveComment'], 'string', 'max' => 500],

            [['operator'], 'string', 'max' => 200],

            [['issueDescription', 'solution'], 'string', 'max' => 1000],

            [['techApproval', 'techApprovedBy'], 'string', 'max' => 50],

            [['ticketId', 'MOPName'], 'unique', 'targetAttribute' => ['ticketId', 'MOPName']],

	    ['ticketId','match','pattern'=>'/^((?!(0))[0-9]{4,5}$)/'],

	    ['MOPName','match','pattern'=>'/^(MOP)(\_)([A-Z][(A-Z)(a-z)\-]+)(\_)((?!(0))[0-9]{4,5})(\_)([A-Z][a-z\-]+)(\_)(([0-2][0-9]|(3)[0-1])(((0)[0-9])|((1)[0-2]))\d{4})(\_)([v][1-9]$)/'],

	    /*['MOPName','match','pattern'=>'/^(MOP)(\_)(Tigo-Bolivia|Millicom-Tanzania|Hutch-SriLanka|Etisalat-SriLanka|Telecom-SriLanka|Airtel-SriLanka|Ooredoo-Maldives|IAF:ALU-India|TATA-India|DTAC-Thailand|TrueMove-Thailand|Millicom-Ghana|Vini-Tahiti|Millicom-Chad|Millicom-Senagal|Safaricom-Kenya|Vodafone-New Zealand|Tigo-Honduras|Intelli-Australia|Tigo-Colombia|Cellcard-Cambodia|Tigo-ElSalvador|Tigo-Paraguay|Smart-Cambodia|Laogw-Laos)(\_)((?!(0))[0-9]{4,5})(\_)([A-Z][a-z\-]+)(\_)(([0-2][0-9]|(3)[0-1])(((0)[0-9])|((1)[0-2]))\d{4})(\_)([v][1-9]$)/'],*/

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'mopId' => 'Mop ID',
            'ticketId' => 'Ticket ID',
            'openDate' => 'Open Date',
            'MOPCusSharedDate' => 'Mopcus Shared Date',
            'MOPCreator' => 'Mopcreator',
            'MOPName' => 'Mopname',
            'operator' => 'Operator',
            'issueDescription' => 'Issue Description',
            'solution' => 'Solution',
            'linkToMOP' => 'Link To Mop',
            'techApproval' => 'Tech Approval',
            'techApprovedBy' => 'Tech Approved By',
            'approvalStatus' => 'Approval Status',
            'approveComment' => 'Approve Comment',
	    'approveAlert' => 'Approve Alert',
        ];
    }

    public function getCreateactivity(){

        return $this->hasOne(Createactivity::className(), ['id_mop' => 'mopId']);

    }

    public function getOperatorsName(){

        return $this->hasOne(Operator::className(),['operatorId'=>'operator']);

    }

    public static function getMopName()
    {

        $mopName = ArrayHelper::map(self::find()->all(), 'mopId', 'MOPName');

        return $mopName;
    }

    public function getCreatorsName(){

        //return $this->hasOne(Creator::className(),['createrId'=>'MOPCreator']);
        return $this->hasOne(User::className(),['id'=>'MOPCreator']);

    }
	
	public function getApproverName(){

        return $this->hasOne(User::className(),['id'=>'techApprovedBy']);

    }

    public static function getName($ticketId){

        $mop = self::find()->where(['ticketId'=>$ticketId])->all();

        return $mop;
    }

    public static function getTicket(){

        $ticket = self::find()->select(['ticketId'])->groupBy(['ticketId'])->all();

        return ArrayHelper::map($ticket,'ticketId', 'ticketId');
    }
	
	public function getSendApprovalAlert() {


        //Pxx$sql = "SELECT mopId,MOPName AS MOPName,linkToMOP,approvalStatus, c.createrMail AS ApproverMail,c.createrName AS ApproverName,a.createrName AS creatorName FROM mop left Join creator c on c.createrId=mop.techApprovedBy left Join creator a on a.createrId=mop.MOPCreator WHERE approvalStatus=0";
        $sql = "SELECT mopId,MOPName AS MOPName,linkToMOP,approvalStatus, c.username AS ApproverMail,c.firstname AS ApproverName,a.firstname AS creatorName FROM mop left Join user c on c.id=mop.techApprovedBy left Join user a on a.id=mop.MOPCreator WHERE approvalStatus=0";
        $connection = Yii::$app->getDb();

        $results = $connection->createCommand($sql)->queryAll();

        if ($results) {

        foreach ($results as $result) {

                if($result['ApproverName'] && $result['ApproverMail']){

                        $send = Yii::$app->mailer->compose()
                                    ->setFrom('support@globalwavenet.com')
                                    ->setTo($result['ApproverMail'])
                                    ->setSubject('MOP Approval Alert')
                                    ->setHtmlBody("Hi $result[ApproverName],<br><br>You have an MOP:$result[MOPName] for approval.<br><br>MOP Creator:$result[creatorName]<br>Link to MOP:$result[linkToMOP]<br><br>Regards,<br>Operation Assistance<br>Wavenet Support")
                                    ->send();

                        if($send){

                            $connection = Yii::$app->getDb();

                            $command = $connection->createCommand("UPDATE mop SET approvalStatus=1 WHERE mopId=$result[mopId]");

                            $command->execute();

			    Yii::$app->readWriteLog->readWriteLog("app\models\MOP Approval Mail Sent",['Receiver'=>$result['ApproverMail']],2);

                         
                        }

                       
                }
            }
        }
    }

    public function getSendApprovalStatusAlert() {


        //Pxx $sql = "SELECT mopId,MOPName AS MOPName,approveComment as Comment,approvalStatus,techApproval, c.createrMail AS CreaterMail,c.createrName AS CreaterName,a.createrMail AS ApproverMail,a.createrName AS ApproverName FROM mop left Join creator c on c.createrId=mop.MOPCreator left Join creator a on a.createrId=mop.techApprovedBy WHERE approveAlert=0";
         $sql = "SELECT mopId,MOPName AS MOPName,approveComment as Comment,approvalStatus,techApproval,c.username AS CreaterMail,c.firstname AS CreaterName,a.username AS ApproverMail,a.firstname AS ApproverName FROM mop left Join user c on c.id=mop.MOPCreator left Join user a on a.id=mop.techApprovedBy WHERE approveAlert=0";
        $connection = Yii::$app->getDb();

        $results = $connection->createCommand($sql)->queryAll();

        if ($results) {

        foreach ($results as $result) {

                if($result['techApproval']=="Approved" OR $result['techApproval']=="Rejected"){

                        $send = Yii::$app->mailer->compose()
                                    ->setFrom('support@globalwavenet.com')
                                    ->setTo(array($result['CreaterMail'],$result['ApproverMail']))
                                    ->setSubject('MOP Approval Alert')
                                    ->setHtmlBody("Hi $result[CreaterName],<br><br>The MOP:$result[MOPName],has been $result[techApproval] by $result[ApproverName].<br><br>Comment:$result[Comment]<br><br>Regards,<br>Operation Assistance<br>Wavenet Support")
                                    ->send();

                        if($send){

                            $connection = Yii::$app->getDb();

                            $command = $connection->createCommand("UPDATE mop SET approveAlert=1 WHERE mopId=$result[mopId]");

                            $command->execute();

			    Yii::$app->readWriteLog->readWriteLog("app\models\MOP MOP Approval Alert Sent",['Receiver'=>[$result['CreaterMail'],$result['ApproverMail']]],2);

                         
                        }

                       
                }
            }
        }
    }
}

controllers/MopController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\NotFoundHttpException;
use app\models\Mop;
use app\models\MopSearch;
use app\controllers\AppController;
use app\models\createForm;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;



class MopController extends Controller
{
    /**
     * {@inheritdoc}
     */
    
   public function behaviors()
    {
        return [
            
    
        ];
    }

    public function beforeAction($action) 
    {
        $this->enableCsrfValidation = false;
        
        return parent::beforeAction($action);
    }

    public function actionMopoperation()
    {
        $searchModel = new MopSearch();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('mopoperation', ['searchModel'=>$searchModel,'dataProvider' => $dataProvider]);
    }

    public function actionCreate(){

        $this->layout = 'popup';

        $model = new Mop();

        if ($model->load(Yii::$app->request->post())) {
           $session = Yii::$app->session;
           $userid = $session['user_id'];
           $model->MOPCreator=(string)$userid;
            if($model->save()){
                Yii::$app->session->setFlash('success', '<B>MOP Record created successfully</B> ');
                Yii::$app->readWriteLog->readWriteLog("app\models\Mop MOP Record created successfully",['TicketId'=>$model->ticketId,'MOP Name'=>$model->MOPName,'MOP Creator'=>$model->creatorsName->firstname],2);
                $model->getSendApprovalAlert();
                $model->ticketId='';
                $model->openDate='';
                $model->MOPCusSharedDate='';
                $model->MOPName='';
                $model->operator='';
                $model->issueDescription='';
                $model->linkToMOP='';
                $model->solution='';
                $model->techApproval='';
                $model->techApprovedBy='';
                $model->approvalStatus='';
                $model->approveComment='';
                return $this->render('createform',['model' => $model]);
            }
            else{

                return $this->render('createform',['model' => $model]);
            }
	        

        } else{

            return $this->render('createform',['model' => $model]);
        }
    }

    public function actionView($id)
    {
        $this->layout = 'popup';

        $model = Mop::findOne($id);

        return $this->render('viewform',['model'=> $model]);
    
    }

    public function actionActivityview($id)
    {
        $this->layout = 'popup';

        $model = Mop::findOne($id);

        return $this->render('activityviewform',['model'=> $model]);
    
    }

    public function actionUpdate($id){

        $this->layout = 'popup';

        $model = Mop::findOne($id);

    if($model->load(Yii::$app->request->post()) && $model->save()){
    Yii::$app->session->setFlash('success', '<B>MOP Record Updated successfully</B> ');
	Yii::$app->readWriteLog->readWriteLog("app\models\Mop MOP Record updated successfully",['TicketId'=>$model->ticketId,'MOP Name'=>$model->MOPName,'MOP Creator'=>$model->creatorsName->firstname],2);

        return $this->render('updateform',['model'=>$model]);

    }
    else{
        return $this->render('updateform',['model'=>$model]);
    }

    }

    public function actionDelete($id){

        $model = Mop::findOne($id);

        if ($model->delete()){

	    Yii::$app->readWriteLog->readWriteLog("app\models\Mop MOP Record deleted",['Ticket ID'=>$model->ticketId,'MOP Name'=>$model->MOPName],2);

            return $this->redirect(['mopoperation']);

        }
    }

    public function actionMopdistribution()
    {
  
        $model = new mop();

        return $this->render('mopdistribution', ['model'=>$model]);
    }
       
    public function actionShowmopdistribution()
    {
        
        $model = new mop();
        
        $model->scenario = mop::SCENARIO_DIST_MOP;
      
         if (Yii::$app->request->isPost) 
        {

            $model->load(Yii::$app->request->post());

            $smonth = \yii\helpers\ArrayHelper::getValue($_POST, 'startDate');
            $emonth = \yii\helpers\ArrayHelper::getValue($_POST, 'endDate');
            $filter = \yii\helpers\ArrayHelper::getValue($_POST, 'filter');

            $sql="SELECT ";

            if ($filter=='')
                    $sql .= "DATE_FORMAT(openDate,'%Y-%M') AS Category,COUNT(mopId) AS Count from mop WHERE DATE_FORMAT(openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' GROUP BY Category";

            if ($filter=='Month')
                    $sql .= "DATE_FORMAT(openDate,'%Y-%M') AS Category,COUNT(mopId) AS Count from mop WHERE DATE_FORMAT(openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' GROUP BY Category";

            if ($filter=='operator')
                    /*$sql .= "operator AS Category,COUNT(mopId) AS Count from mop WHERE DATE_FORMAT(openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' GROUP BY Category";*/
                    $sql .= "o.operatorName AS Category,COUNT(m.mopId) AS Count from mop m, operator o WHERE DATE_FORMAT(m.openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' and m.operator = o.operatorId GROUP BY m.operator";

            if ($filter=='MOPCreator')
                    //Pxx $sql .= "c.creatorName AS Category,COUNT(m.mopId) AS Count from mop m, creator c WHERE DATE_FORMAT(m.openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' and m.MOPCreator = c.createrId GROUP BY m.MOPCreator";
                     $sql .= "c.firstname AS Category,COUNT(m.mopId) AS Count from mop m, user c WHERE DATE_FORMAT(m.openDate,'%Y-%m') BETWEEN '$smonth' AND '$emonth' and m.MOPCreator = c.id GROUP BY m.MOPCreator";


           $connection = Yii::$app->getDb();
         
            try {
                
                $result = $connection->createCommand($sql)->queryAll();

                $data = array();
                    foreach ($result as $row) {
                    $data[] = $row;
                }

                //$data=array_reverse($data);

		//$data=sort($data);

                print json_encode($data);
                
                exit;

                } catch (Exception $e) {
            }
        }

    }

    /*public function actionApprove($id){

        $model = Mop::findOne($id);

        $connection = Yii::$app->getDb();

        $command = $connection->createCommand("UPDATE mop SET techApproval='Approved' WHERE mopId=$id");

        $command->execute();

        return $this->redirect(['mopoperation']);
    }*/

    public function actionApprove($id)
    {

        $this->layout = 'popup';

        $model = Mop::findOne($id);

        if($model->load(Yii::$app->request->post())){

            if($model->techApproval =="1"){

                $model->techApproval = "Approved";

                $model->save();
                Yii::$app->session->setFlash('success', '<B>MOP Record approved successfully</B> ');
		Yii::$app->readWriteLog->readWriteLog("app\models\Mop MOP Approved",['Ticket ID'=>$model->ticketId,'MOP Name'=>$model->MOPName,'Approved By'=>$model->techApprovedBy,'Approval Status'=>$model->techApproval],2);

		$model->getSendApprovalStatusAlert();

                return $this->render('approveform',['model'=>$model]);

            }elseif($model->techApproval =="2"){

                $model->techApproval = "Rejected";

                $model->save();
                Yii::$app->session->setFlash('success', '<B>MOP Record rejected successfully</B> ');
		Yii::$app->readWriteLog->readWriteLog("app\models\Mop MOP Rejected",['Ticket ID'=>$model->ticketId,'MOP Name'=>$model->MOPName,'Approved By'=>$model->techApprovedBy,'Approval Status'=>$model->techApproval],2);

		$model->getSendApprovalStatusAlert();

                return $this->render('approveform',['model'=>$model]);

            }

        }
        else{
            
            return $this->render('approveform',['model'=>$model]);
        }
    
    }

}

views/mop/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MopSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="mop-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'mopId') ?>

    <?= $form->field($model, 'ticketId') ?>

    <?= $form->field($model, 'openDate') ?>

    <?= $form->field($model, 'MOPCusSharedDate') ?>

    <?= $form->field($model, 'MOPCreator') ?>

    <?php // echo $form->field($model, 'MOPName') ?>

    <?php // echo $form->field($model, 'operator') ?>

    <?php // echo $form->field($model, 'issueDescription') ?>

    <?php // echo $form->field($model, 'solution') ?>

    <?php // echo $form->field($model, 'activityScheduleDate') ?>

    <?php // echo $form->field($model, 'linkToMOP') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/mop/updateform.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use kartik\date\DatePicker;
use kartik\datetime\DateTimePicker;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Rca */
/* @var $form yii\widgets\ActiveForm */
?>                    
                    <div class="modal-body">
                    <?php if (Yii::$app->session->hasFlash('success')): ?>
                                <div class="alert alert-success alert-dismissable">
                                    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                    <?= Yii::$app->session->getFlash('success') ?>
                                </div>
                            <?php endif; ?>

                            <?php if (Yii::$app->session->hasFlash('error')): ?>
                                <div class="alert alert-danger alert-dismissable">
                                    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                    <?= Yii::$app->session->getFlash('error') ?>
                                </div>
                            <?php endif; ?>   
                            <!-- <form class="form-horizontal"> -->
                            <?php $form = ActiveForm::begin(['options' => ['id' => 'Update-form','class'=>'form-horizontal']]) ?>
                                <div class="row">
                                    <div class="box-body boxpad">

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Ticket ID</label>
                                                <div class="col-sm-8" >
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->ticketId;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Opened Date</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->openDate;?>'>      
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">MOP Name</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->MOPName;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">MOP Customer Shared Date</label>
                                                <!-- <div class="col-sm-10"> -->
                                                    <?=$form->field($model, 'MOPCusSharedDate',['options' => ['class' => 'col-sm-8','id' => 'MOPCusSharedDate']])->label(false)->widget(DatePicker::classname(), ['options' => ['placeholder' => 'YYYY/MM/DD'],
                                                            'pluginOptions' => [
                                                                'autoclose' => true,
                                                                'format' => 'yyyy-mm-dd'
                                                            ]
                                                        ]);?>
                                                <!-- </div> -->
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label class="col-sm-4 control-label">Technical Approval</label>
                                                    <!--?= $form->field($model, 'techApproval',['options' => ['class' => 'col-sm-10']])->label(false)->widget(Select2::classname(), ['data' => ['Approved' => 'Approved', 'Not Approved' => 'Not Approved'],'options' => ['placeholder' => 'Technical Approval'],'pluginOptions' => ['allowClear' => true],]); ?-->
                                                    <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->techApproval;?>'>
                                                    </div>
                                                </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label class="col-sm-4 control-label">Approve By</label>
                                                    <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo @$model->approverName->firstname;?>'>
                                                    </div>
                                                </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Operator</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->operatorsName->operatorName;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Issue Description</label>
                                                <!-- <div class="col-sm-10"> -->
                                                    <?= $form->field($model, 'issueDescription',['options' => ['class' => 'col-sm-8']])->textarea(['rows' => '3','maxlength' => true,'placeholder' => 'Description'])->label(false);?>
                                                <!-- </div> -->
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Solution</label>
                                                <!-- <div class="col-sm-10"> -->
                                                    <?= $form->field($model, 'solution',['options' => ['class' => 'col-sm-8']])->textarea(['rows' => '3','maxlength' => true,'placeholder' => 'Solution'])->label(false);?>
                                                <!-- </div> -->
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Activity Schedule Date</label>
                                                <!-- <div class="col-sm-10"> -->
                                                    <!--?=$form->field($model, 'activityScheduleDate',['options' => ['class' => 'col-sm-8','id' => 'activityScheduleDate']])->label(false)->widget(DateTimePicker::classname(), ['options' => ['placeholder' => 'YYYY/MM/DD HH:MM'],
                                                            'pluginOptions' => [
                                                                'autoclose' => true,
                                                                'format' => 'yyyy-mm-dd hh:ii'
                                                            ]
                                                        ]);?-->
                                                <!-- </div> -->
                                                <div class="col-sm-8" >
                                                    <input type="text" disabled class="form-control" value='<?php echo @$model->createactivity->scheduleactivity->scheduleTimeSL;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">MOP Creator</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo $model->creatorsName->firstname;?>'>
                                                </div>
                                            </div>
                                        </div>

					<div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Approve Comments</label>
                                                <div class="col-sm-8">
                                                    <input type="text" disabled class="form-control" value='<?php echo @$model->approveComment;?>'>
                                                </div>
                                            </div>
                                        </div>

                                        <div id="" class="col-md-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label class="col-sm-4 control-label">Link to MOP</label>
                                                <!-- <div class="col-sm-10"> -->
                                                    <?= $form->field($model, 'linkToMOP',['options' => ['class' => 'col-sm-8']])->textInput(['maxlength' => true,'placeholder' => 'URL'])->label(false);?>
                                                <!-- </div> -->
                                            </div>
                                        </div>

                                    </div>
                                </div> 
                            <!-- </form> -->                                                       
                        </div>

                        <div class="modal-footer">
                            <!-- ?= Html::button('Close', ['class' => 'btn btn-default','name' => 'closeUpdate', 'id' => 'closeUpdate']) ?-->
                            <?= Html::submitButton('Save Changes', ['class' => 'btn btn-primary','name' => 'update', 'id' => 'update']) ?>
                        </div>
                        <?php ActiveForm::end() ?>
<?php
$script = <<< JS
$( document ).ready(function() {
       
        $('#closeUpdate').click(function() {
             window.parent.closeUpdateModal();
         });  
    });
JS;

$this->registerJs($script);
?>